language: cpp

sudo: required
dist: trusty

addons:
    apt:
        packages:
            - libsdl2-dev
            - python-ply

script:
    - cd scripts/create_bindings/ && sudo python create_bindings.py
    - cd ../../build/linux/ && make all