language: cpp

sudo: required
dist: trusty

addons:
    apt:
        packages:
            - libsdl2-dev
            - python-ply

script:
    - sudo apt-get -yq --no-install-suggests --no-install-recommends --force-yes install python-ply
    - cd scripts/create_bindings/ && python create_bindings.py
    - cd ../../build/linux/ && make all